name: "intermate_dbt"
version: "1.0"
config-version: 2

profile: "intermate_bigquery"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  intermatedbt:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table

    fact_tables:
      +schema: analytics
      +materialized: incremental

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt", "intermate_macros"]
